// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"gitee.com/phillip_huang/redis-demo/service/rpc/user/internal/logic"
	"gitee.com/phillip_huang/redis-demo/service/rpc/user/internal/svc"
	"gitee.com/phillip_huang/redis-demo/service/rpc/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) UserRegister(ctx context.Context, in *user.UserRegisterRequest) (*user.UserRegisterResponse, error) {
	l := logic.NewUserRegisterLogic(ctx, s.svcCtx)
	return l.UserRegister(in)
}

func (s *UserServer) GetUserInfo(ctx context.Context, in *user.GetUserInfoRequest) (*user.GetUserInfoResponse, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
