// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterRequest struct {
	Username string `json:"username,omitempty"` // omitempty表示json序列化时如果字段值为类型零值，忽略该字段
	Password string `json:"password,omitempty"`
	Phone    string `json:"phone,omitempty"`
	Email    string `json:"email,omitempty"`
}

type UserRegisterResponse struct {
	ErrorCode    int32  `json:"errorCode,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
}

type UserLoginRequest struct {
	Username string `json:"username,omitempty"` // omitempty表示json序列化时如果字段值为类型零值，忽略该字段
	Password string `json:"password,omitempty"`
	Phone    string `json:"phone,omitempty"`
	Email    string `json:"email,omitempty"`
}

type UserLoginResponse struct {
	ErrorCode    int32  `json:"errorCode,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	Token        string `json:"token,omitempty"`
}

type GetUserInfoResponse struct {
	ErrorCode    int32  `json:"errorCode,omitempty"`
	ErrorMessage string `json:"errorMessage,omitempty"`
	Id           string `json:"Id,omitempty"`
	Username     string `json:"username,omitempty"`
	Gender       string `json:"gender,omitempty"`
	Phone        string `json:"phone,omitempty"`
	Email        string `json:"email,omitempty"`
	Nickname     string `json:"nickname,omitempty"`
	Birthday     string `json:"birthday,omitempty"`
}
